version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '13307:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  web:
    build: .
    command: /bin/sh -c "rm -f /server/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SERVER_DATABASE_USERNAME: root
      SERVER_DATABASE_HOST: db
      SERVER_DATABASE_PORT: 3306
    volumes:
      - .:/server
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - '13001:3000'
    depends_on:
      - db
    links:
      - db
    tty: true
    stdin_open: true
